djcrud/crudapp/blog_posts/urls.py
app_name = 'blog_posts'

from django.conf.urls import url
from blog_posts import views

urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^new$', views.post_create, name='post_new'),
    url(r'^edit/(?P<pk>\d+)$', views.post_update, name='post_edit'),
    url(r'^delete/(?P<pk>\d+)$', views.post_delete, name='post_delete'),
]

djcrud/crudapp/crudapp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path('', include('blog_posts.urls', namespace='blog_posts')),
]

djcrud/crudapp/blog_posts/models.py
# -*- coding: utf-8 -*-



#from __future__ import unicode_literals
from django.urls import reverse

from django.db import models


# Create your models here.
class blog_posts(models.Model):
    title = models.CharField(max_length=400)
    tag = models.CharField(max_length=50)
    author = models.CharField(max_length=120)

def __unicode__(self):
    return self.title

def get_post_url(self):
    return reverse('post_edit', kwargs={'pk': self.pk})

djcrud/crudapp/blog_posts/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect, get_object_or_404
from django.forms import ModelForm

from blog_posts.models import blog_posts

# Create your views here.
app_name = 'blog_posts'

class PostsForm(ModelForm):
    class Meta:
        model = blog_posts
        fields = ['id', 'title', 'author']

def post_list(request, template_name='blog_posts/post_list.html'):
    posts = blog_posts.objects.all()
    data = {}
    data['object_list'] = posts
    return render(request, template_name, data)

def post_create(request, template_name='blog_posts/post_form.html'):
    form = PostsForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('blog_posts:post_list')
    return render(request, template_name, {'form': form})

def post_update(request, pk, template_name='blog_posts/post_form.html'):
    post = get_object_or_404(blog_posts, pk=pk)
    form = PostsForm(request.POST or None, instance=post)
    if form.is_valid():
        form.save()
        return redirect('blog_posts:post_list')
    return render(request, template_name, {'form': form})

def post_delete(request, pk, template_name='blog_posts/post_delete.html'):
    post = get_object_or_404(blog_posts, pk=pk)
    if request.method == 'POST' :
        post.delete()
        return redirect('blog_posts:post_list')
    return render(request, template_name, {'object': post})

djcrud/crudapp/blog_posts/templates/blog_posts/post_delete.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
    <title>Django CRUD application delete!</title>
  </head>
  <body>
    <div class="container">
      <form method="post">{% csrf_token %}
        Are you sure you want to delete "{{ object }}" ?
        <input class="btn btn-primary" type="submit" value="Ok" />
      </form>
    </div>
  </body>
</html>

djcrud/crudapp/blog_posts/templates/blog_posts/post_form.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
    <title>Django CRUD application frm!</title>
  </head>
  <body>
    <div class="container">
      <form  method="post">{% csrf_token %}
        {{ form.as_p }}
        <input class="btn btn-primary" type="submit" value="Ok" />
      </form>
    </div>
  </body>
</html>

djcrud/crudapp/blog_posts/templates/blog_posts/post_list.html
 <!DOCTYPE html>
<html lang="fr">

<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>

		{% comment %} 	  
	    <meta charset="utf-8">
	    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css"> 
        {% endcomment %}


	<title>Django CRUD application list!</title>
</head>
<body>

	<div class="container">
			<h1>Blog Post Liste!</h1>
			<ul>
			{% for post in object_list %}
			  <div class="row">
			  <div class="col-sm-2"><li><p>Post ID: <a href="{% url "blog_posts:post_edit" post.id %}">{{ post.id }}</a></p></div>
			  <div class="col-sm-3"><p>Titre: {{ post.title }}</p></div>
			  <div class="col-sm-3"><p>Auteur: {{ post.author }}</p></div>
			  <div class="col-sm-2"><a href="{% url "blog_posts:post_delete" post.id %}">Supprimer</a></div>
			  </li>
			  
			  </div>
			{% endfor %}
		    </ul>
			<a href="{% url "blog_posts:post_new" %}">Nouveau record</a>
	</div>





	
</body>
</html>

djcrud/crudapp/blog_posts/templates/blog_posts/post_listBck.html
 <!DOCTYPE html>
<html lang="fr">

<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>

		{% comment %} 	  
	    <meta charset="utf-8">
	    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css"> 
        {% endcomment %}


	<title>Django CRUD application list!</title>
</head>
<body>
	<div class="container">
			<h1>Blog Post Liste!</h1>
			<ul>
				{% for post in object_list %}
				<li><p>Post ID: <a href="{% url "blog_posts:post_edit" post.id %}">{{ post.id }}</a></p>
				<p>Titre: {{ post.title }}</p>
				<a href="{% url "blog_posts:post_delete" post.id %}">Supprimer</a>
				</li>
				{% endfor %}
			</ul>
                <a href="{% url "blog_posts:post_new" %}">Nouveau record</a> 
	</div>


	<div class="container">
		<div class="row">
			  <div class="col-sm-2">1 of 5</div>
			  <div class="col-sm-2">2 of 5</div>
			  <div class="col-sm-4">3 of 5</div>
		</div>
	</div>





	
</body>
</html>